kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami2
  namespace: default
  labels:
    app: whoami
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          imagePullPolicy: Always

      restartPolicy: Always
