kind: Deployment
apiVersion: apps/v1
metadata:
  name: sampleapp
  namespace: default
  labels:
    app: sampleapp
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: azitmentor/sampleapp:1.1.0
          imagePullPolicy: Always

      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: sampleapp-service
  namespace: default
  labels:
    app: sampleapp
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: sampleapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sampleapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:

  rules:
    - host: or2.ezcal.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  sampleapp-service
                port:
                  number: 80
