version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build:
    working_directory: /app
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
            apt install docker.io
            docker build ./sampleapp -t azitmentor/sampleapp
      # - restore_cache:
      #     keys:
      #       - v1-{{ .Branch }}
      #     paths:
      #       - /caches/app.tar
      # - run:
      #     name: Load Docker image layer cache
      #     command: |
      #       set +o pipefail
      #       docker load -i /caches/app.tar | true
