version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build:
    working_directory: /app
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:  docker build -t azitmentor/sampleapp:latest ./sampleapp
      - deploy:
          name: Push application Docker image
          command: |
            echo $dockerpw
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login -u azitmentor -p $dockerpw
              docker push azitmentor/sampleapp:latest
            fi
  deploytokub:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KCONFIG
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment.yml
          resource-name: service/sampleapp
          show-kubectl-command: true

      - kubernetes/update-container-image:
          container-image-updates: 'sampleapp=azitmentor/sampleapp:latest'
          get-rollout-status: true
          resource-name: deployment/sampleapp

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploytokub:
          requires:
            - build
 